import 'bootstrap/dist/css/bootstrap.css'
import { Inter, Roboto, Poppins } from "next/font/google";
import './globals.css'
import Navbar from '@/ui/navbar/Navbar'
import Footer from '@/ui/footer/Footer'
import BootstrapClient from '@/ui/bootstrapClient/bootstrap'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
        <Navbar/>
        {children}
        <Footer/>
        <BootstrapClient/>
        </div>
        </body>
    </html>
  )
}
